outbox:
  schema: mysql
  tableName: outbox
database:
  host: db
  port: 3306
  username: admin
  password: pass1234
  name: db

publisher:
  aws:
    accessKey: dummy
    secretKey: dummy
    sns:
      endpoint: http://localstack:4566
      topics:
        - transform:
            type: outbox
            outbox:
              aggregateType: test-sns
          topicArn: arn:aws:sns:ap-northeast-1:000000000000:test-sns
        - transform:
            type: outbox
            outbox:
              aggregateType: sns
          topicArn: arn:aws:sns:ap-northeast-1:000000000000:test-sns
