version: '3.7'
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/src/
      - ~/.gitconfig:/.gitconfig
      - ~/.ssh/:/home/user/.ssh/
    tty: true
    networks:
      - default
  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass1234
      TZ: Asia/Tokyo
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      timeout: 5s
      retries: 10
    networks:
      - default
  localstack:
    image: localstack/localstack:2.3.2
    environment:
      DEBUG: false
      DOCKER_HOST: unix:///var/run/docker.sock
      SERVICES: sns,sqs
      AWS_DEFAULT_REGION: ap-northeast-1
      DISABLE_CORS_CHECKS: 1
      DISABLE_CUSTOM_CORS_S3: 1
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tools/localstack.sh:/etc/localstack/init/ready.d/localstack.sh
    healthcheck:
      test:
        - CMD
        - 'curl'
        - 'http://localhost:4566/_localstack/health'
      interval: 2s
      start_period: 20s
      retries: 10
      timeout: 10s
volumes:
  mysql:
  localstack:
networks:
  default:
