// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nonchan7720/go-storage-to-messenger/pkg/ent/outbox"
)

// Outbox is the model entity for the Outbox schema.
type Outbox struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AggregateType holds the value of the "aggregate_type" field.
	AggregateType string `json:"aggregate_type,omitempty"`
	// AggregateID holds the value of the "aggregate_id" field.
	AggregateID string `json:"aggregate_id,omitempty"`
	// Event holds the value of the "event" field.
	Event string `json:"event,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload []byte `json:"payload,omitempty"`
	// RetryAt holds the value of the "retry_at" field.
	RetryAt *time.Time `json:"retry_at,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount   int `json:"retry_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Outbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case outbox.FieldPayload:
			values[i] = new([]byte)
		case outbox.FieldID, outbox.FieldRetryCount:
			values[i] = new(sql.NullInt64)
		case outbox.FieldAggregateType, outbox.FieldAggregateID, outbox.FieldEvent:
			values[i] = new(sql.NullString)
		case outbox.FieldRetryAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Outbox fields.
func (o *Outbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case outbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int64(value.Int64)
		case outbox.FieldAggregateType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_type", values[i])
			} else if value.Valid {
				o.AggregateType = value.String
			}
		case outbox.FieldAggregateID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aggregate_id", values[i])
			} else if value.Valid {
				o.AggregateID = value.String
			}
		case outbox.FieldEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event", values[i])
			} else if value.Valid {
				o.Event = value.String
			}
		case outbox.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil {
				o.Payload = *value
			}
		case outbox.FieldRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field retry_at", values[i])
			} else if value.Valid {
				o.RetryAt = new(time.Time)
				*o.RetryAt = value.Time
			}
		case outbox.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				o.RetryCount = int(value.Int64)
			}
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Outbox.
// This includes values selected through modifiers, order, etc.
func (o *Outbox) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// Update returns a builder for updating this Outbox.
// Note that you need to call Outbox.Unwrap() before calling this method if this Outbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Outbox) Update() *OutboxUpdateOne {
	return NewOutboxClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Outbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Outbox) Unwrap() *Outbox {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Outbox is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Outbox) String() string {
	var builder strings.Builder
	builder.WriteString("Outbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", o.ID))
	builder.WriteString("aggregate_type=")
	builder.WriteString(o.AggregateType)
	builder.WriteString(", ")
	builder.WriteString("aggregate_id=")
	builder.WriteString(o.AggregateID)
	builder.WriteString(", ")
	builder.WriteString("event=")
	builder.WriteString(o.Event)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", o.Payload))
	builder.WriteString(", ")
	if v := o.RetryAt; v != nil {
		builder.WriteString("retry_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", o.RetryCount))
	builder.WriteByte(')')
	return builder.String()
}

// Outboxes is a parsable slice of Outbox.
type Outboxes []*Outbox
