name: Release

on:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: write
  packages: write

env:
  DOCKERHUB_USERNAME: ncsnozominishinohara
  IS_RELEASED: ${{ startsWith(github.ref, 'refs/tags/v') }}
  IMAGE_NAME: go-storage-to-messenger

jobs:
  release-and-push:
    name: Release And Push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tag name to release tag name
        if: env.IS_RELEASED == 'true'
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
      - name: tag name to release tag name
        if: env.IS_RELEASED != 'true'
        run: |
          echo "VERSION=${{ github.sha }}" >> "$GITHUB_ENV"
      - name: output release tag name
        id: set_env
        run: |
          echo "tag=${{ env.VERSION }}" >> "$GITHUB_OUTPUT"
      - uses: docker/setup-buildx-action@v2
      - name: Log in ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Repository for release
        uses: docker/build-push-action@v4
        if: env.IS_RELEASED == 'true'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ncsnozominishinohara/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ncsnozominishinohara/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha,scope=go-mysql-to-sns
          cache-to: type=gha,mode=max,scope=go-mysql-to-sns

      - name: Push to Repository for non release
        uses: docker/build-push-action@v4
        if: env.IS_RELEASED != 'true'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ncsnozominishinohara/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          cache-from: type=gha,scope=go-mysql-to-sns
          cache-to: type=gha,mode=max,scope=go-mysql-to-sns
